import * as fs from 'fs';
import * as path from 'path';

const SOURCE_DIR = '/Users/ayushtomar/Downloads/listingx for website/LISTING PICTURES (all)';
const R2_MANIFEST_PATH = path.join(process.cwd(), 'docs/catalog-onboarding/R2_ASSET_MIGRATION_MANIFEST.md');

// Helper to determine product types and business dependencies
function classifyRecord(folderName: string, parentFolder: string, infoContent: string) {
  let classification = 'PRODUCT';
  let decision = 'TECHNICALLY_COMPLETE_PENDING_PACKAGING_AND_ASSETS';

  if (parentFolder.includes('F&F cars') || parentFolder.includes('Motivations Quotes') || parentFolder.includes('Car split') || parentFolder.includes('Ronaldo Split') || parentFolder.includes('Split Anime') || parentFolder.includes('Football jerseys')) {
    classification = 'DESIGN_VARIANT';
    decision = 'BUSINESS_CONFIRMATION_REQUIRED';
  } else if (parentFolder.includes('Anime (4 variations)') || parentFolder.includes('bookmarks (3, 3 variations)')) {
    classification = 'PRODUCT_VARIANT';
    decision = 'BUSINESS_CONFIRMATION_REQUIRED';
  }

  // Check for missing data
  let price = '0';
  let isMissingPrice = false;
  if (!infoContent) {
    decision = 'MISSING_DATA';
    isMissingPrice = true;
  } else if (infoContent.toLowerCase().includes('generate') || infoContent.includes('rupees') && !infoContent.includes('price')) {
    decision = 'BUSINESS_CONFIRMATION_REQUIRED';
    isMissingPrice = true;
  } else {
    // Attempt basic parse
    const priceMatch = infoContent.match(/price.*?(\d+)/i);
    if (priceMatch) {
      price = priceMatch[1];
    } else {
      isMissingPrice = true;
      decision = 'BUSINESS_CONFIRMATION_REQUIRED';
    }
  }

  return { classification, decision, price, isMissingPrice };
}

async function run() {
  console.log('--- CATALOG DRY-RUN IMPORTER ---');
  console.log(`Source: ${SOURCE_DIR}`);
  console.log('Mode: DRY RUN (No DB mutations, No R2 mutations)\n');

  if (!fs.existsSync(SOURCE_DIR)) {
    console.error(`Source directory not found: ${SOURCE_DIR}`);
    process.exit(1);
  }

  let catalogReport = [];
  let r2Manifest = [
    '# R2 Asset Migration Manifest',
    '',
    '*Generated by dry-run-importer.ts*',
    '',
    '## Asset Approval State Machine',
    'Assets follow this strict pipeline before reaching production:',
    '`SOURCE` → `PROGRAMMATICALLY_CHECKED` → `VISUAL_REVIEW_REQUIRED` → `APPROVED_FOR_R2` → `UPLOADED` → `VERIFIED`',
    '',
    '*Terminal states:* `DO_NOT_USE`',
    '',
    '## Asset Listing',
    '| Source Path | Proposed R2 Key | Status | Migration Status |',
    '|---|---|---|---|'
  ];

  const categories = fs.readdirSync(SOURCE_DIR).filter(f => fs.statSync(path.join(SOURCE_DIR, f)).isDirectory());

  let totalFolders = 0;
  let missingData = 0;
  let businessConfirmation = 0;

  for (const category of categories) {
    const catPath = path.join(SOURCE_DIR, category);
    const subitems = fs.readdirSync(catPath);

    for (const item of subitems) {
      const itemPath = path.join(catPath, item);
      if (!fs.statSync(itemPath).isDirectory()) continue;

      // Handle nesting (e.g. F&F cars has subfolders)
      const isGroupFolder = ['F&F cars (8 variations)', 'Football jerseys (10 variations)', 'Motivations Quotes (30 variations)', 'Anime (4 variations)', 'Car split (7 variations)', 'Ronaldo Split (6 variations)', 'Split Anime (7 variations)', 'bookmarks (3, 3 variations)', 'No category'].includes(item);

      if (isGroupFolder) {
        const variants = fs.readdirSync(itemPath).filter(f => fs.statSync(path.join(itemPath, f)).isDirectory());
        for (const variant of variants) {
          const variantPath = path.join(itemPath, variant);
          processFolder(variantPath, item, variant);
        }
      } else {
        processFolder(itemPath, category, item);
      }
    }
  }

  function processFolder(dirPath: string, parentName: string, folderName: string) {
    totalFolders++;
    const files = fs.readdirSync(dirPath);
    let infoContent = '';
    const infoFile = files.find(f => f.toLowerCase() === 'info.txt');
    
    if (infoFile) {
      infoContent = fs.readFileSync(path.join(dirPath, infoFile), 'utf-8');
    }

    const { classification, decision, price, isMissingPrice } = classifyRecord(folderName, parentName, infoContent);
    
    if (decision === 'MISSING_DATA') missingData++;
    if (decision === 'BUSINESS_CONFIRMATION_REQUIRED') businessConfirmation++;

    const title = folderName.replace(/[-_]/g, ' ');
    const sku = `FM-PEN-${Math.floor(Math.random() * 1000)}`;

    catalogReport.push({
      source_path: `${parentName}/${folderName}`,
      proposed_identity: title,
      classification,
      selling_price: isMissingPrice ? 'UNVERIFIED' : `₹${price}`,
      status: decision,
      missing_fields: isMissingPrice ? ['price', 'dimensions', 'weight'] : ['dimensions', 'weight'],
      business_decisions_required: classification === 'DESIGN_VARIANT' ? ['Grouping logic (Variant vs Product)', 'Packaging'] : ['Packaging']
    });

    // Asset manifest
    const imageFiles = files.filter(f => f.match(/\.(jpg|jpeg|png)$/i));
    for (const img of imageFiles) {
      const r2Key = `catalog/${parentName.toLowerCase().replace(/[^a-z0-9]/g, '-')}/${img}`;
      r2Manifest.push(`| \`${parentName}/${folderName}/${img}\` | \`${r2Key}\` | REQUIRES_REVIEW (PosterNet branding check) | DO_NOT_UPLOAD |`);
    }
  }

  console.log(`Found ${totalFolders} total leaf folders.\n`);
  
  const readyRecords = catalogReport.filter(r => r.status === 'TECHNICALLY_COMPLETE_PENDING_PACKAGING_AND_ASSETS');
  
  console.log(`Status Summary:`);
  console.log(`- TECHNICALLY_COMPLETE_PENDING_PACKAGING_AND_ASSETS: ${readyRecords.length}`);
  console.log(`- MISSING_DATA: ${missingData}`);
  console.log(`- BUSINESS_CONFIRMATION_REQUIRED: ${businessConfirmation}\n`);

  if (readyRecords.length > 0) {
    console.log('The following records are technically complete (pending packaging and asset approval):');
    console.log(readyRecords);
    console.log();
  }

  console.log('Sample of Catalog Import Report:');
  console.table(catalogReport.slice(0, 5));

  // Write R2 Manifest
  fs.writeFileSync(R2_MANIFEST_PATH, r2Manifest.join('\n'));
  console.log(`\nCreated R2 Asset Migration Manifest at: docs/catalog-onboarding/R2_ASSET_MIGRATION_MANIFEST.md`);
  console.log('\nDry-run complete. No database mutations occurred. No R2 uploads occurred.');
}

run().catch(console.error);
