import * as fs from 'fs';
import * as path from 'path';

const SOURCE_DIR = '/Users/ayushtomar/Downloads/listingx for website/LISTING PICTURES (all)';
const R2_MANIFEST_PATH = path.join(process.cwd(), 'docs/catalog-onboarding/R2_ASSET_MIGRATION_MANIFEST.md');

async function run() {
  console.log('--- CATALOG DRY-RUN IMPORTER (BUSINESS ANALYSIS MODE) ---');
  console.log(`Source: ${SOURCE_DIR}`);
  console.log('Mode: DRY RUN (No DB mutations, No R2 mutations)\n');

  if (!fs.existsSync(SOURCE_DIR)) {
    console.error(`Source directory not found: ${SOURCE_DIR}`);
    process.exit(1);
  }

  let r2Manifest = [
    '# R2 Asset Migration Manifest',
    '',
    '*Generated by dry-run-importer.ts*',
    '',
    '## Asset Approval State Machine',
    'Assets follow this strict pipeline before reaching production:',
    '`SOURCE` → `PROGRAMMATICALLY_CHECKED` → `VISUAL_REVIEW_REQUIRED` → `APPROVED_FOR_R2` → `UPLOADED` → `VERIFIED`',
    '',
    '*Terminal states:* `DO_NOT_USE`',
    '',
    '## Asset Listing',
    '| Source Path | Proposed R2 Key | Status | Migration Status |',
    '|---|---|---|---|'
  ];

  const categories = fs.readdirSync(SOURCE_DIR).filter(f => fs.statSync(path.join(SOURCE_DIR, f)).isDirectory());

  // Counters
  let totalFolders = 0;
  let totalAssets = 0;
  
  let countValidPrice = 0;
  let countMissingPrice = 0;
  let countPlaceholderPrice = 0;
  
  let countSkuPresent = 0;
  let countSkuMissing = 0;
  
  let countInfoTxtPresent = 0;
  let countInfoTxtMissing = 0;
  
  let countPackagingComplete = 0;
  let countPackagingMissing = 0;
  
  let countMockupComplete = 0;
  let countMockupMissing = 0;
  
  let countAssetApproved = 0;
  let countAssetReviewRequired = 0;
  
  let countAmbiguousVariant = 0;

  for (const category of categories) {
    const catPath = path.join(SOURCE_DIR, category);
    const subitems = fs.readdirSync(catPath);

    for (const item of subitems) {
      const itemPath = path.join(catPath, item);
      if (!fs.statSync(itemPath).isDirectory()) continue;

      const isGroupFolder = ['F&F cars (8 variations)', 'Football jerseys (10 variations)', 'Motivations Quotes (30 variations)', 'Anime (4 variations)', 'Car split (7 variations)', 'Ronaldo Split (6 variations)', 'Split Anime (7 variations)', 'bookmarks (3, 3 variations)', 'No category'].includes(item);

      if (isGroupFolder) {
        const variants = fs.readdirSync(itemPath).filter(f => fs.statSync(path.join(itemPath, f)).isDirectory());
        for (const variant of variants) {
          const variantPath = path.join(itemPath, variant);
          processFolder(variantPath, item, variant);
        }
      } else {
        processFolder(itemPath, category, item);
      }
    }
  }

  function processFolder(dirPath: string, parentName: string, folderName: string) {
    totalFolders++;
    const files = fs.readdirSync(dirPath);
    let infoContent = '';
    const infoFile = files.find(f => f.toLowerCase() === 'info.txt');
    
    if (infoFile) {
      countInfoTxtPresent++;
      infoContent = fs.readFileSync(path.join(dirPath, infoFile), 'utf-8');
    } else {
      countInfoTxtMissing++;
    }

    // Pricing parsing
    if (!infoContent) {
      countMissingPrice++;
    } else if (infoContent.toLowerCase().includes('generate') || infoContent.includes('rupees') && !infoContent.match(/price.*?\d+/i)) {
      countPlaceholderPrice++;
    } else if (infoContent.match(/price.*?\d+/i)) {
      countValidPrice++;
    } else {
      countMissingPrice++;
    }

    // SKU parsing
    if (infoContent.match(/sku.*?\w+/i)) {
      countSkuPresent++;
    } else {
      countSkuMissing++;
    }

    // Ambiguous variant? (Any folder that is part of a series)
    if (parentName.includes('variations') || parentName.includes('Split') || parentName.includes('jerseys') || parentName.includes('Quotes') || parentName.includes('bookmarks')) {
      countAmbiguousVariant++;
    }

    // Packaging parsing - NONE of the files contain explicit L x W x H x W (packed)
    countPackagingMissing++;

    // Mockup parsing - NONE of the files contain explicit print area geometry/assets
    countMockupMissing++;

    // Asset manifest
    const imageFiles = files.filter(f => f.match(/\.(jpg|jpeg|png)$/i));
    for (const img of imageFiles) {
      totalAssets++;
      countAssetReviewRequired++; // Automatically requires review
      
      const r2Key = `catalog/${parentName.toLowerCase().replace(/[^a-z0-9]/g, '-')}/${img}`;
      r2Manifest.push(`| \`${parentName}/${folderName}/${img}\` | \`${r2Key}\` | VISUAL_REVIEW_REQUIRED (PosterNet branding check) | DO_NOT_UPLOAD |`);
    }
  }

  console.log(`\n=== AUTHORITATIVE INVENTORY COUNTS ===`);
  console.log(`Total leaf folders: ${totalFolders}`);
  console.log(`Total assets/images: ${totalAssets}`);
  console.log(`info.txt-present count: ${countInfoTxtPresent}`);
  console.log(`info.txt-missing count: ${countInfoTxtMissing}`);
  console.log(`valid-price count: ${countValidPrice}`);
  console.log(`missing-price count: ${countMissingPrice}`);
  console.log(`placeholder-price count: ${countPlaceholderPrice}`);
  console.log(`SKU-present count: ${countSkuPresent}`);
  console.log(`SKU-missing count: ${countSkuMissing}`);
  console.log(`ambiguous-variant-structure count: ${countAmbiguousVariant}`);
  console.log(`packaging-complete count: ${countPackagingComplete}`);
  console.log(`packaging-missing count: ${countPackagingMissing}`);
  console.log(`mockup-complete count: ${countMockupComplete}`);
  console.log(`mockup-missing count: ${countMockupMissing}`);
  console.log(`asset-approved count: ${countAssetApproved}`);
  console.log(`asset-review-required count: ${countAssetReviewRequired}`);

  // Write R2 Manifest
  fs.writeFileSync(R2_MANIFEST_PATH, r2Manifest.join('\n'));
  console.log(`\nCreated R2 Asset Migration Manifest at: docs/catalog-onboarding/R2_ASSET_MIGRATION_MANIFEST.md`);
  console.log('\nDry-run complete. No database mutations occurred. No R2 uploads occurred.');
}

run().catch(console.error);
